@startuml estados del cliente

[*] --> ingresado
state ingresado{
	
}


ingresado --> verificado : buscarCliente(string dni)


state verificado{

}

verificado --> registrado :registrarCliente()

state registrado{
	
}



verificado --> [*]
registrado --> [*] 

@enduml